/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateBrandRequest } from '../model/models';
import { CreatedBrandResponse } from '../model/models';
import { GetAllBrandResponse } from '../model/models';
import { GetBrandByIdResponse } from '../model/models';
import { GetTransmissionById400Response } from '../model/models';
import { UpdateBrandRequest } from '../model/models';
import { UpdateBrandResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateBrandRequestParams {
    createBrandRequest: CreateBrandRequest;
}

export interface DeleteBrandByIdRequestParams {
    id: number;
}

export interface GetBrandByIdRequestParams {
    id: number;
}

export interface UpdateBrandByIdRequestParams {
    id: number;
    updateBrandRequest: UpdateBrandRequest;
}


export interface BrandControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createBrand(requestParameters: CreateBrandRequestParams, extraHttpRequestParams?: any): Observable<CreatedBrandResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteBrandById(requestParameters: DeleteBrandByIdRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllBrands(extraHttpRequestParams?: any): Observable<Array<GetAllBrandResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getBrandById(requestParameters: GetBrandByIdRequestParams, extraHttpRequestParams?: any): Observable<GetBrandByIdResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateBrandById(requestParameters: UpdateBrandByIdRequestParams, extraHttpRequestParams?: any): Observable<UpdateBrandResponse>;

}
